### ISSUE TITLE
unixfs fails to make on OS X

### ISSUE THREAD

**Issue by AlecZadikian9001** [osxfuse/filesystems#19]
OS X 10.9.4 with latest Xcode Tools installed with Xcode 6

I tried to compile unixfs to enable UFS2 support for OS X per a tutorial I found here: https://wiki.gutzmann.com/confluence/pages/viewpage.action?pageId=6651931

Here is a copy of the instructions:

Download and install OSXFUSE from http://osxfuse.github.com/. Reboot the system.
Download this ZIP file from https://github.com/osxfuse/filesystems.
Download and install XCode from http://developer.apple.com/xcode/. This is a prerequisite for step 10.
Download and install XCode.
Launch XCode.
Open XCode preferences.
Go to tab "Downloads".
Locate "Command Line Tools".
Click "Install" and enter your credentials.
Locate the directory "unixfs" in the unzipped source code downloaded in step 2.
Open a terminal window.
Enter "sudo -s" and supply your admin password.
Copy "unixfs" (see step 4) to "/usr/local/include/osxfuse/" (cp -R unixfs /usr/local/include/osxfuse/).
Enter "cd /usr/local/include/osxfuse/unixfs/ufs".
Enter "ln -s /usr/local/include/osxfuse/fuse".
Enter "make".
Create a mount point, for example "mkdir usb".
Enter "diskutil list" and look for the identifier of the external drive containing the UFS volume (for me it was "disk1s1").
Enter "./ufs --dmg /dev/disk1s1 --type ufs2 usb", replacing "disk1s1" with the actual identifier und "usb" with the mount point created in step 11.
Enter "df -h" to see if the volume has been mounted.

On the tenth step, where I enter "make", I get the following build error:

ufs.c:759:1: error: unused function 'ufs_validate_entry' [-Werror,-Wunused-function] ufs_validate_entry(struct super_block\* sb, char\* base, unsigned offset, ^ 1 error generated. make: **\* [ufs.o] Error 1

**Comment by bfleischer** [comment]
This repository contains legacy demo file systems that are unmaintained. Therefore I'm closing the issue. Please refer to https://github.com/macfuse/demo for maintained demo file systems.
