### ISSUE TITLE
I don't know how to judge that the file is completely finished.

### ISSUE THREAD

**Issue by Martin812** [osxfuse/filesystems#32]
If I copy a larger file, It will call release once every 25.2mb, instead of calling it until I have finished writing it, so I want to know how to accurately determine that the file is completely written, because I need to do something after the file copy is completed.thanks a lot.

**Comment by bfleischer** [comment]
This repository contains legacy demo file systems that are unmaintained. Therefore I'm closing the issue. Please refer to https://github.com/macfuse/demo for maintained demo file systems.
