### ISSUE TITLE
ext4fs or btrfs are missing

### ISSUE THREAD

**Issue by dominix** [osxfuse/filesystems#33]
Hi everyone, 
today modern computing involve exchanging file over usb disks, keys, whatever.
so when using osxfuse the use of ext4 or btrfs is a must have.
is there any plan to have ext4fs or btrfs support on osxfuse ?

**Comment by nikbex-sno** [comment]
Have same problem, file system unrecognised!
Mainly Linux ext4. Thanks

**Comment by bfleischer** [comment]
The filesystems repository contains only demo file systems. There are ext4 implementations for osxfuse out there. One example would be this one: https://github.com/gerard/ext4fuse.

Please note that FUSE provides the tools required for file system developers to build file systems. FUSE on its own does not allow you to mount ext4 volumes or any other format. FUSE is a building block that is used by third party developers to implement actual file system drivers.

**Comment by nikbex-sno** [comment]
Thanks
