### ISSUE TITLE
handling of korean characters

### ISSUE THREAD

**Issue by mnirahd** [osxfuse/filesystems#34]
I've a directory which has couple of files with korean characters.

1) [영상] 2016040421 kbs2 2TV아침 TV Review, KBS드라마 달달한 장면들 - 안재욱 소유진의 '아이가 다섯' (권ᄋ?002e006dp4.mp4
2) conflict_movetotrash_[영상] 2016040421 kbs2 2TV아침 TV Review, KBS드라마 달달한 장면들 : 안재욱 소유진의 아이가_2019-07-30-14-21-39.txt

Now if I mount this directory using LoopFS, and When I navigate to LoopFS, it will not show any contents in LoopFS for this directory. Moreover, if I try to create a folder inside that directory, it will flash created folder for a moment, and then make it disappeared. However these folder are created on actual folder correctly.

**Comment by bfleischer** [comment]
This repository contains legacy demo file systems that are unmaintained. Therefore I'm closing the issue. Please refer to https://github.com/macfuse/demo for maintained demo file systems.
