### ISSUE TITLE
Add support for FilterFS

### ISSUE THREAD

**Issue by mardukbp** [osxfuse/filesystems#35]
[FilterFS](https://github.com/eddyp/filterfs) is a FUSE-based virtual filesystem that allows filtering existing filesystems.

**Comment by bfleischer** [comment]
Please raise the issue with the FilterFS author. The author of FilterFS needs to add support for macOS, not the other way around.

**Comment by bfleischer** [comment]
Please raise the issue with the FilterFS author. The author of FilterFS needs to add support for macOS, not the other way around.
