### ISSUE TITLE
Problem with deleting .docx files

### ISSUE THREAD

**Issue by andreipro1002** [osxfuse/filesystems#36]
Hello,
It seems to be a problem with deleting the .docx files using the LoopbackFS sample project on OSX Catalina. When deleting the .docx file, the callback **removeItemAtPath** is not called, and after the file is gone, a temp file .fuse_hidden0000 appears in the same directory. Do you know any solutions for this? Thanks in advance.

**Comment by bfleischer** [comment]
This repository contains legacy demo file systems that are unmaintained. Therefore I'm closing the issue. Please refer to https://github.com/macfuse/demo for maintained demo file systems.
