### ISSUE TITLE
ObjC LoopbackFS fails to mount in macOS Big sur

### ISSUE THREAD

**Issue by vijaynr** [osxfuse/filesystems#42]
Hi, I was trying out the example Loopback FS in macOS 11 (beta 9), I'm facing the issue where the mount failed with the below error message.

```
Error: Error Domain=GMUserFileSystemErrorDomain Code=1003 "Internal FUSE error (rc=1) while attempting to mount the file system. For now, the best way to diagnose is to look for error messages using Console." UserInfo={NSLocalizedDescription=Internal FUSE error (rc=1) while attempting to mount the file system. For now, the best way to diagnose is to look for error messages using Console.}, userInfo={ 
    NSLocalizedDescription = "Internal FUSE error (rc=1) while attempting to mount the file system. For now, the best way to diagnose is to look for error messages using Console.";
```

And the console outputs these, but it's the same in macOS 10.15.x. So I guess this is not the problem. 

![image](https://user-images.githubusercontent.com/17999110/95371377-c16ca800-08f7-11eb-91de-5aa3c34eaaf7.png)

Is there a way to fix this by changing the mount options?  The same example works for me in macOS 10.15.7 and I have an APFS file system if that matters. I'm facing this issue after installing 3.11.2 version of osxfuse.

**Comment by vijaynr** [comment]
I just figured out, that it is due to the fact the kernel extension was not loading as it was not approved in System Preferences. But I don't see anything in System Preferences -> Security and Privacy -> General. I tried installing and uninstalling multiple times. It does not show up in System Preferences to approve the extension and fails mounting always.

**Comment by bfleischer** [comment]
Does not appear be an issue with LoopbackFS, so I'm closing the ticket.
