### ISSUE TITLE
Linux File Server / Macs workstations

### ISSUE THREAD

**Issue by KrzyhooG** [osxfuse/filesystems#47]
I'll warn you in advance that I'm not a Linux super admin or programmer, more of an amateur loafing around overseeing and maintaining a Micro file server (RedHatE) and a couple of Mac clients in my studio. Using sshfs I connected a resource from another external server(sftp) and from the Linux server, everything can be seen, everything works, unfortunately the Mac clients can't see it. I tried another way, I connected the resource with sshfs and using macFuse I was able to reach the content on another internal server this time Mac. I now wanted to make the resource available via this Mac server to all other Mac clients by mounting it on the main Micro server (RedHatE). Now Linux cannot see the mounted resource on the Mac server... What am I doing wrong? Maybe the assumption itself is wrong? How to do it correctly, can you advise me? Maybe it can't be done at all? I am very much asking for help. Greetings

**Comment by bfleischer** [comment]
This repository contains legacy demo file systems that are unmaintained. Therefore I'm closing the issue. Please refer to https://github.com/macfuse/demo for maintained demo file systems.

**Comment by bfleischer** [comment]
This repository contains legacy demo file systems that are unmaintained. Therefore I'm closing the issue. Please refer to https://github.com/macfuse/demo for maintained demo file systems.
