### ISSUE TITLE
error: variable 'usb2' set but not used / error: variable 'usb3' set but not used

### ISSUE THREAD

**Issue by bixfrankonis** [osxfuse/filesystems#50]
I know there's a bunch of ufs threads already, and the ufs support at this point is basically unsupported, but anyone else run into these errors and know how to fix them?

**Comment by bfleischer** [comment]
This repository contains legacy demo file systems that are unmaintained. Therefore I'm closing the issue. Please refer to https://github.com/macfuse/demo for maintained demo file systems.
